### ISSUE TITLE
Game loads multiplayer map instead of E1M3

### ISSUE THREAD

**Issue by Alevam-Inc** [timbergeron/QSS-M#23]
When I try to play single player, the game loads multiplayer maps instead.

**Comment by timbergeron** [comment]
Hey there! Sorry for the delayed response. It turns out this issue was caused by a bug I introduced in a much older version. If you upgrade to the latest build from the GitHub Actions workflow artifacts, the problem should be resolved. The bug was related to the `sv_map_rotation "dm2 dm5 dm6"` cvar, which lets you easily set up a map rotation for a deathmatch server.
